import {
  LayoutDashboard,
  Users,
  GraduationCap,
  Briefcase,
  Building2,
  MapPin,
  Bus,
  CreditCard,
  Megaphone,
  Calendar,
  UserCheck,
  Wallet,
  BellRing,
  BookOpen,
  Trophy,
  Users2,
  Hotel,
  FileText,
  BookMarked,
  ClipboardList,
  Landmark,
  BookCopy,
} from 'lucide-react';

export const navigationConfig = {
  SUPER_ADMIN: [
    { label: 'Super Admin Dashboard', path: '/super-admin/dashboard',  icon: LayoutDashboard },
    { label: 'User Directory',        path: '/users',                   icon: Users },
    { label: 'Students',              path: '/students',                icon: GraduationCap },
    { label: 'Staff',                 path: '/staff',                   icon: Briefcase },
    { label: 'Departments',           path: '/departments',             icon: Building2 },
    { label: 'Venues',                path: '/venues',                  icon: MapPin },

    // ── Your features ──────────────────────────────────────────────
    { label: 'Books',                 path: '/books',                   icon: BookOpen },
    { label: 'Clubs',                 path: '/clubs',                   icon: Users2 },
    { label: 'Sports',                path: '/sports',                  icon: Trophy },
    { label: 'Sport Teams',           path: '/sport-teams',             icon: Users2 },
    { label: 'Venue Booking',         path: '/venue-booking',          icon: Landmark },
    { label: 'Certificate',           path: '/select-student',             icon: FileText },
    { label: 'Add Document',          path: '/add-document',            icon: FileText },
    { label: 'Handout',               path: '/handout',                 icon: BookMarked },
    { label: 'Letterhead',            path: '/letterhead',              icon: FileText },
    { label: 'Upload Materials',      path: '/upload-materials',        icon: ClipboardList },
    { label: 'Study Materials',       path: '/display-materials',         icon: BookMarked },
    { label: 'Payment Management',    path: '/payment-management',      icon: Wallet },
    { label: 'Hostel',                path: '/hostel',                  icon: Hotel },
    { label: 'Exams',                 path: '/exams',                   icon: ClipboardList },
    { label: 'Subjects',              path: '/subjects',                icon: BookCopy },

    // ── Friend features ────────────────────────────────────────────
    { label: 'Transport',             path: '/transport',               icon: Bus },
    { label: 'Fee Payment',           path: '/fee-payment',             icon: CreditCard },
    { label: 'Event Notices',         path: '/event-notices',           icon: Megaphone },
    { label: 'Event Booking',         path: '/events',                  icon: Calendar },
    { label: 'Alumni Profiles',       path: '/alumni',                  icon: UserCheck },
    { label: 'Alumni Jobs',           path: '/alumni-jobs',             icon: Briefcase },
    { label: 'System Announcements',  path: '/system-announcements',    icon: BellRing },
  ],

  SUB_ADMIN: [
    { label: 'Dashboard',             path: '/dashboard',               icon: LayoutDashboard },
    { label: 'Students',              path: '/students',                icon: GraduationCap },
    { label: 'Staff',                 path: '/staff',                   icon: Briefcase },
    { label: 'Departments',           path: '/departments',             icon: Building2 },
    { label: 'Venues',                path: '/venues',                  icon: MapPin },
    { label: 'Books',                 path: '/books',                   icon: BookOpen },
    { label: 'Clubs',                 path: '/clubs',                   icon: Users2 },
    { label: 'Sports',                path: '/sports',                  icon: Trophy },
    { label: 'Sport Teams',           path: '/sport-teams',             icon: Users2 },
    { label: 'Venue Booking',         path: '/venue-booking',          icon: Landmark },
    { label: 'Certificate',           path: '/select-student',             icon: FileText },
    { label: 'Add Document',          path: '/add-document',            icon: FileText },
    { label: 'Handout',               path: '/handout',                 icon: BookMarked },
    { label: 'Letterhead',            path: '/letterhead',              icon: FileText },
    { label: 'Upload Materials',      path: '/upload-materials',        icon: ClipboardList },
    { label: 'Study Materials',       path: '/display-materials',         icon: BookMarked },
    { label: 'Payment Management',    path: '/payment-management',      icon: Wallet },
    { label: 'Hostel',                path: '/hostel',                  icon: Hotel },
    { label: 'Exams',                 path: '/exams',                   icon: ClipboardList },
    { label: 'Subjects',              path: '/subjects',                icon: BookCopy },
    { label: 'Transport',             path: '/transport',               icon: Bus },
    { label: 'Fee Payment',           path: '/fee-payment',             icon: CreditCard },
    { label: 'Event Notices',         path: '/event-notices',           icon: Megaphone },
    { label: 'Event Booking',         path: '/events',                  icon: Calendar },
    { label: 'Alumni Profiles',       path: '/alumni',                  icon: UserCheck },
    { label: 'Alumni Jobs',           path: '/alumni-jobs',             icon: Briefcase },
    { label: 'System Announcements',  path: '/system-announcements',    icon: BellRing },
  ],

  FINANCE: [
    { label: 'Dashboard',             path: '/dashboard',               icon: LayoutDashboard },
    { label: 'Fee Payment',           path: '/fee-payment',             icon: CreditCard },
    { label: 'Payment Management',    path: '/payment-management',      icon: Wallet },
    { label: 'Students',              path: '/students',                icon: GraduationCap },
    { label: 'Staff',                 path: '/staff',                   icon: Briefcase },
    { label: 'Departments',           path: '/departments',             icon: Building2 },
    { label: 'Venues',                path: '/venues',                  icon: MapPin },
    { label: 'Transport',             path: '/transport',               icon: Bus },
    { label: 'Event Notices',         path: '/event-notices',           icon: Megaphone },
    { label: 'System Announcements',  path: '/system-announcements',    icon: BellRing },
  ],

  FACULTY: [
    { label: 'Dashboard',             path: '/dashboard',               icon: LayoutDashboard },
    { label: 'Students',              path: '/students',                icon: GraduationCap },
    { label: 'Departments',           path: '/departments',             icon: Building2 },
    { label: 'Venues',                path: '/venues',                  icon: MapPin },
    { label: 'Books',                 path: '/books',                   icon: BookOpen },
    { label: 'Upload Materials',      path: '/upload-materials',        icon: ClipboardList },
    { label: 'Study Materials',       path: '/display-materials',         icon: BookMarked },
    { label: 'Exams',                 path: '/exams',                   icon: ClipboardList },
    { label: 'Subjects',              path: '/subjects',                icon: BookCopy },
    { label: 'Transport',             path: '/transport',               icon: Bus },
    { label: 'Event Notices',         path: '/event-notices',           icon: Megaphone },
    { label: 'Event Booking',         path: '/events',                  icon: Calendar },
    { label: 'System Announcements',  path: '/system-announcements',    icon: BellRing },
  ],

  TEACHER: [
    { label: 'Dashboard',             path: '/dashboard',               icon: LayoutDashboard },
    { label: 'Students',              path: '/students',                icon: GraduationCap },
    { label: 'Departments',           path: '/departments',             icon: Building2 },
    { label: 'Venues',                path: '/venues',                  icon: MapPin },
    { label: 'Books',                 path: '/books',                   icon: BookOpen },
    { label: 'Upload Materials',      path: '/upload-materials',        icon: ClipboardList },
    { label: 'Study Materials',       path: '/display-materials',         icon: BookMarked },
    { label: 'Exams',                 path: '/exams',                   icon: ClipboardList },
    { label: 'Subjects',              path: '/subjects',                icon: BookCopy },
    { label: 'Transport',             path: '/transport',               icon: Bus },
    { label: 'Event Notices',         path: '/event-notices',           icon: Megaphone },
    { label: 'Event Booking',         path: '/events',                  icon: Calendar },
    { label: 'System Announcements',  path: '/system-announcements',    icon: BellRing },
  ],

  STUDENT: [
    { label: 'Dashboard',             path: '/dashboard',               icon: LayoutDashboard },
    { label: 'Fee Payment',           path: '/fee-payment',             icon: CreditCard },
    { label: 'Books',                 path: '/books',                   icon: BookOpen },
    { label: 'Clubs',                 path: '/clubs',                   icon: Users2 },
    { label: 'Sports',                path: '/sports',                  icon: Trophy },
    { label: 'Sport Teams',           path: '/sport-teams',             icon: Users2 },
    { label: 'Study Materials',       path: '/display-materials',         icon: BookMarked },
    { label: 'Hostel',                path: '/hostel',                  icon: Hotel },
    { label: 'Departments',           path: '/departments',             icon: Building2 },
    { label: 'Venues',                path: '/venues',                  icon: MapPin },
    { label: 'Transport',             path: '/transport',               icon: Bus },
    { label: 'Event Notices',         path: '/event-notices',           icon: Megaphone },
    { label: 'Event Booking',         path: '/events',                  icon: Calendar },
    { label: 'System Announcements',  path: '/system-announcements',    icon: BellRing },
  ],
};
