import {
  LayoutDashboard,
  Users,
  GraduationCap,
  Briefcase,
  Building2,
  MapPin,
  Bus,
  CreditCard,
  Megaphone,
  Calendar,
  UserCheck,
  Wallet,
  BellRing,
} from 'lucide-react';

export const navigationConfig = {
  SUPER_ADMIN: [
    { label: 'Super Admin Dashboard', path: '/super-admin/dashboard', icon: LayoutDashboard },
    { label: 'User Directory', path: '/users', icon: Users },
    { label: 'Students', path: '/students', icon: GraduationCap },
    { label: 'Staff', path: '/staff', icon: Briefcase },
    { label: 'Departments', path: '/departments', icon: Building2 },
    { label: 'Venues', path: '/venues', icon: MapPin },
    { label: 'Transport', path: '/transport', icon: Bus },
    { label: 'Fee Payment', path: '/fee-payment', icon: CreditCard },
    { label: 'Payment Management', path: '/payment-management', icon: Wallet },
    { label: 'Event Notices', path: '/event-notices', icon: Megaphone },
    { label: 'Event Booking', path: '/events', icon: Calendar },
    { label: 'Alumni Profiles', path: '/alumni', icon: UserCheck },
    { label: 'Alumni Jobs', path: '/alumni-jobs', icon: Briefcase },
    { label: 'System Announcements', path: '/system-announcements', icon: BellRing },
  ],
  SUB_ADMIN: [
    { label: 'Dashboard', path: '/dashboard', icon: LayoutDashboard },
    { label: 'Students', path: '/students', icon: GraduationCap },
    { label: 'Staff', path: '/staff', icon: Briefcase },
    { label: 'Departments', path: '/departments', icon: Building2 },
    { label: 'Venues', path: '/venues', icon: MapPin },
    { label: 'Transport', path: '/transport', icon: Bus },
    { label: 'Fee Payment', path: '/fee-payment', icon: CreditCard },
    { label: 'Event Notices', path: '/event-notices', icon: Megaphone },
    { label: 'Event Booking', path: '/events', icon: Calendar },
    { label: 'Alumni Profiles', path: '/alumni', icon: UserCheck },
    { label: 'Alumni Jobs', path: '/alumni-jobs', icon: Briefcase },
    { label: 'System Announcements', path: '/system-announcements', icon: BellRing },
  ],
  FINANCE: [
    { label: 'Dashboard', path: '/dashboard', icon: LayoutDashboard },
    { label: 'Fee Payment', path: '/fee-payment', icon: CreditCard },
    { label: 'Students', path: '/students', icon: GraduationCap },
    { label: 'Staff', path: '/staff', icon: Briefcase },
    { label: 'Departments', path: '/departments', icon: Building2 },
    { label: 'Venues', path: '/venues', icon: MapPin },
    { label: 'Transport', path: '/transport', icon: Bus },
    { label: 'Event Notices', path: '/event-notices', icon: Megaphone },
    { label: 'Event Booking', path: '/events', icon: Calendar },
    { label: 'System Announcements', path: '/system-announcements', icon: BellRing },
  ],
  FACULTY: [
    { label: 'Dashboard', path: '/dashboard', icon: LayoutDashboard },
    { label: 'Students', path: '/students', icon: GraduationCap },
    { label: 'Departments', path: '/departments', icon: Building2 },
    { label: 'Venues', path: '/venues', icon: MapPin },
    { label: 'Transport', path: '/transport', icon: Bus },
    { label: 'Event Notices', path: '/event-notices', icon: Megaphone },
    { label: 'Event Booking', path: '/events', icon: Calendar },
    { label: 'System Announcements', path: '/system-announcements', icon: BellRing },
  ],
  TEACHER: [
    { label: 'Dashboard', path: '/dashboard', icon: LayoutDashboard },
    { label: 'Students', path: '/students', icon: GraduationCap },
    { label: 'Departments', path: '/departments', icon: Building2 },
    { label: 'Venues', path: '/venues', icon: MapPin },
    { label: 'Transport', path: '/transport', icon: Bus },
    { label: 'Event Notices', path: '/event-notices', icon: Megaphone },
    { label: 'Event Booking', path: '/events', icon: Calendar },
    { label: 'System Announcements', path: '/system-announcements', icon: BellRing },
  ],
  STUDENT: [
    { label: 'Dashboard', path: '/dashboard', icon: LayoutDashboard },
    { label: 'Fee Payment', path: '/fee-payment', icon: CreditCard },
    { label: 'Departments', path: '/departments', icon: Building2 },
    { label: 'Venues', path: '/venues', icon: MapPin },
    { label: 'Transport', path: '/transport', icon: Bus },
    { label: 'Event Notices', path: '/event-notices', icon: Megaphone },
    { label: 'Event Booking', path: '/events', icon: Calendar },
    { label: 'System Announcements', path: '/system-announcements', icon: BellRing },
  ],
};
